#!/bin/sh -x

VERSION=$1
if test -z "$VERSION"; then
   echo $0: usage: $0 version
   exit 1
fi

if test -n "$(git status --porcelain)"; then
   echo $0: git status is wordy, you probably want to stash and note your branch
   exit 2
fi
git tag $VERSION -m 'release $VERSION'
git checkout --detach
git clean -fxd
git rm .gitignore
git rm -r debian
git rm release
echo $VERSION > VERSION
sed -e "s/@VERSION@/$VERSION/" README.in > README
git rm README.in
libtoolize -ic
autoreconf
git add -A
git commit -m "release $VERSION"
git tag release/$VERSION -m "release $VERSION processed for git archive"

git checkout master
