.\" Copyright 1987 by the Massachusetts Institute of Technology
.\" All rights reserved.  The file /usr/include/zephyr/mit-copyright.h
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)zwrite.1	6.1 (MIT) 7/9/87
.\"
.TH ZWRITE 1 "February 6, 1988"
.SH NAME
zwrite \- write to another user
.SH SYNOPSIS
.B zwrite
[
.BI -a
] [
.BI -d
] [
.BI -v
] [
.BI -q
] [
.BI -u
] [
.BI -o
] [
.BI -c
class ] [
.BI -i
instance ] [
.BI user \ ...
] [
.BI -m
.BI message
]
.SH DESCRIPTION
.I Zwrite
sends a message from you to another user through the
.I zephyr(1)
notification service.  The user must have subscribed to messages of
the appropriate class and instance using the
.I zctl(1)
program.
.PP
.I Zwrite
understands the following options.
.TP 12
.B \-a
Causes
.I zwrite
to send the message authenticated, using
.I kerberos
to perform the authentication.  This is the default.
.TP
.B \-d
Causes
.I zwrite
to send the message nonauthenticated.
.TP
.B \-v
Causes
.I zwrite
to print what type of message it is sending, and whether or not it was
successful.
.TP
.B \-q
Forces
.I zwrite
to suppress information about whether or not the message was sent.
.TP
.B \-u
Sends an urgent message.  This changes the
.I zephyr
instance of the message to ``URGENT''.
.TP
.B \-o
Causes
.I zwrite
to ignore the Zephyr variables \fIzwrite-class\fR and \fIzwrite-inst\fR
when picking a default class and instance.
.TP
.B \-c
Allows a user to specify a different class for the message.  This allows
a message to be sent to a large group of people with some degree of
security.  See
.I zephyr(1)
and
.I zephyrd(8)
for a description of how to restrict access to classes.  When this option
is specified, the message is sent to recipient "*" unless an additional
list of recipients is specified.
.TP
.B \-i
Allows a user to specify a different instance than the default.
When this option is used, the message is sent to recipient "*" unless an
additional list of recipients is specified.  This allows a message to be
sent to a large group of people (e.g. a development group) just by having
the members group to messages of class "MESSAGE", the specified instance,
and recipient "*".
.TP
.B \-m
.I Zwrite
sends the remaining arguments on the command line as the message.
.PP
If the
.I \-m
option is not specified, the user is prompted for the message to be
sent.  The message may be terminated by typing ^D or ``.'' on a line
by itself.
.PP
The default class for messages is ``MESSAGE'', and the default instance
is ``PERSONAL''.  These defaults can be changed by setting the Zephyr
variables \fIzwrite-class\fR and \fIzwrite-inst\fR, respectively.
.PP
If the Zephyr variable \fIzephyr-signature\fR is set, its contents are used
to augment the user's username in the message. 
.SH SEE ALSO
kerberosintro(1), zctl(1), zephyr(1), zwgc(1), zhm(8), zephyrd(8)
.br
`Zephyr Notification Service'
.SH AUTHOR
.PP
.br
Robert S. French (MIT-Project Athena)
.sp
Copyright (c) 1987 by the Massachusetts Institute of Technology
.br
See
.I zephyr(1)
for a full copyright notice.
