.\" Copyright 1987 by the Massachusetts Institute of Technology
.\" All rights reserved.  The file /usr/include/zephyr/mit-copyright.h
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)zstat.8	6.1 (MIT) 7/9/87
.\"
.TH ZSTAT 8 "July 30, 1987"
.UC 6
.SH NAME
zstat \- display Zephyr statistics
.SH SYNOPSIS
.B zstat
[
.BI -h
] [
.BI -s
] [
.BI host \ ...
]
.SH DESCRIPTION
.I Zstat
is used to display statistics about a HostManager,
.I hm(8),
or Zephyr Server
.I zephyrd(8).
.TP 12
.B \-h
is used to indicate that only HostManager statistics should be displayed.
.TP
.B \-s
is used to indicate that only server statistics should be displayed.
.TP
If no hosts are specified, the current host is assumed.
.SH SEE ALSO
zctl(1), zephyr(1), zhide(1), znol(1), zwgc(1), hm(8), zephyrd(8)
.br
`Zephyr Notification Service'
.SH AUTHOR
.PP
Robert S. French (MIT-Project Athena)
.sp
Copyright (c) 1987 by the Massachusetts Institute of Technology
.br
See
.I zephyr(1)
for a full copyright notice.
