#!/bin/csh -f

# This file is part of the Project Athena Zephyr Notification System.
# It is one of the source files comprising zwgc, the Zephyr WindowGram
# client.
#
#      Created by:     Marc Horowitz <marc@athena.mit.edu>
#
#      $Source$
#      $Author$
#
#      Copyright (c) 1989 by the Massachusetts Institute of Technology.
#      For copying and distribution information, see the file
#      "mit-copyright.h".
#
set rcsid_generate_stack_instance="$Header$"
cat zephyr/mit-copyright.h > /dev/null

set source=/afs/athena.mit.edu/astaff/project/zephyr/@sys/zwgc/zwgc.dev

if (z$1x == zx) then
	echo "usage: generate_stack_instance <typename> [<include file>]"
	exit 1
endif
if (-r $source/stack.h) then
else
	echo "generate_stack_instance: unable to open" $source/stack.h
	exit 2
endif

if (z$2x == zx) then
	echo > $1_stack.h
else
	echo "#include" '"'$2'"' > $1_stack.h
endif
sed "s/TYPE_T/$1/g" $source/stack.h >> $1_stack.h
