.\" Copyright 1987 by the Massachusetts Institute of Technology
.\" All rights reserved.  The file /usr/include/zephyr/mit-copyright.h
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)zephyrd.8	6.1 (MIT) 7/9/87
.\"
.TH ZEPHYRD 8 "July 9, 1987"
.SH NAME
zephyrd \- Zephyr server daemon
.SH SYNOPSIS
.B zephyrd
.SH DESCRIPTION
.SH SEE ALSO
zephyr(1), hm(8)
.SH AUTHOR
.PP
John T. Kohl, MIT Project Athena
.sp
Copyright (c) 1987 by the Massachusetts Institute of Technology
.br
See
.I zephyr(1)
for a full copyright notice.
