/* h/config.h.  Generated by configure.  */
/* h/config.h.in.  Generated automatically from configure.in by autoheader.  */
/* Define to compile with Hesiod support. */
/* #undef HAVE_HESIOD */

/* Define to compile with Kerberos support. */
#define HAVE_KRB4 1

/* Define to compile with Kerberos v5 support. */
#define HAVE_KRB5 1

/* Define to 1 if `enc_part2' is member of `krb5_ticket'. */
#define HAVE_KRB5_TICKET_ENC_PART2 1

/* Define to 1 if `keyblock.enctype' is member of `krb5_creds'. */
#define HAVE_KRB5_CREDS_KEYBLOCK_ENCTYPE 1

/* Define to 1 if you have the `krb5_c_make_checksum' function. */
#define HAVE_KRB5_C_MAKE_CHECKSUM 1

/* Define to 1 if you have the `krb5_cc_set_default_name' function. */
#define HAVE_KRB5_CC_SET_DEFAULT_NAME 1

/* Define to 1 if `krb5_auth_con_getauthenticator' takes a double pointer third arg. */
#define KRB5_AUTH_CON_GETAUTHENTICATOR_TAKES_DOUBLE_POINTER 1

/* Define to 1 if you have the <krb5_err.h> header file. */
/* #undef HAVE_KRB5_ERR_H */

/* Define to 1 if you have the `krb5_free_data' function. */
#define HAVE_KRB5_FREE_DATA 1

/* Define to 1 if you have the <krb5/ss.h> header file. */
/* #undef HAVE_KRB5_SS_H */

/* Define to 1 if you have the `krb_get_err_text' function. */
#define HAVE_KRB_GET_ERR_TEXT 1

/* Define to 1 if you have the `krb_log' function. */
#define HAVE_KRB_LOG 1

/* Define to compile with ares support. */
/* #undef HAVE_ARES */

/* Define to a signed 32-bit integral type. */
#define ZEPHYR_INT32 int

/* Define if you have the System Resource Controller library. */
/* #undef HAVE_SRC */

/* Define to "unsigned long" if your system headers don't. */
/* #undef ulong */

/* Define to a temporary directory on your system. */
#define FOUND_TMP "/var/tmp/"

/* Define to the type of the host system. */
#define MACHINE_TYPE "x86_64-unknown-linux-gnu"

/* Define if `regcomp' exists and works. */
/* #undef HAVE_REGCOMP */


/* Define if the `getpgrp' function takes no argument. */
#define GETPGRP_VOID 1

/* Define if you don't have `vprintf' but do have `_doprnt.' */
/* #undef HAVE_DOPRNT */

/* Define if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define if you have the `gethostid' function. */
#define HAVE_GETHOSTID 1

/* Define if you have the `getlogin' function. */
#define HAVE_GETLOGIN 1

/* Define if you have the `getpgid' function. */
#define HAVE_GETPGID 1

/* Define if you have the `getsid' function. */
#define HAVE_GETSID 1

/* Define if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define if you have the `krb5_cc_set_default_name' function. */
#define HAVE_KRB5_CC_SET_DEFAULT_NAME 1

/* Define if `keyblock.enctype' is member of `krb5_creds'. */
#define HAVE_KRB5_CREDS_KEYBLOCK_ENCTYPE 1

/* Define if you have the `krb5_c_make_checksum' function. */
#define HAVE_KRB5_C_MAKE_CHECKSUM 1

/* Define if you have the <krb5_err.h> header file. */
/* #undef HAVE_KRB5_ERR_H */

/* Define if you have the `krb5_free_data' function. */
#define HAVE_KRB5_FREE_DATA 1

/* Define if `enc_part2' is member of `krb5_ticket'. */
#define HAVE_KRB5_TICKET_ENC_PART2 1

/* Define if you have the `krb_get_err_text' function. */
#define HAVE_KRB_GET_ERR_TEXT 1

/* Define if you have the `krb_log' function. */
#define HAVE_KRB_LOG 1

/* Define if you have the `44bsd' library (-l44bsd). */
/* #undef HAVE_LIB44BSD */

/* Define if you have the `curses' library (-lcurses). */
#define HAVE_LIBCURSES 1

/* Define if you have the `dl' library (-ldl). */
#define HAVE_LIBDL 1

/* Define if you have the `gen' library (-lgen). */
/* #undef HAVE_LIBGEN */

/* Define if you have the `nsl' library (-lnsl). */
/* #undef HAVE_LIBNSL */

/* Define if you have the `readline' library (-lreadline). */
#define HAVE_LIBREADLINE 1

/* Define if you have the `resolv' library (-lresolv). */
/* #undef HAVE_LIBRESOLV */

/* Define if you have the `socket' library (-lsocket). */
/* #undef HAVE_LIBSOCKET */

/* Define if you have the `w' library (-lw). */
/* #undef HAVE_LIBW */

/* Define if you have the `lrand48' function. */
#define HAVE_LRAND48 1

/* Define if you have the <malloc.h> header file. */
#define HAVE_MALLOC_H 1

/* Define if you have the `memcpy' function. */
#define HAVE_MEMCPY 1

/* Define if you have the `memmove' function. */
#define HAVE_MEMMOVE 1

/* Define if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define if you have the <paths.h> header file. */
#define HAVE_PATHS_H 1

/* Define if you have the `putenv' function. */
#define HAVE_PUTENV 1

/* Define if you have the `random' function. */
#define HAVE_RANDOM 1

/* Define if you have the <sgtty.h> header file. */
#define HAVE_SGTTY_H 1

/* Define if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define if you have the `strchr' function. */
#define HAVE_STRCHR 1

/* Define if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define if you have the <sys/cdefs.h> header file. */
#define HAVE_SYS_CDEFS_H 1

/* Define if you have the <sys/file.h> header file. */
#define HAVE_SYS_FILE_H 1

/* Define if you have the <sys/filio.h> header file. */
/* #undef HAVE_SYS_FILIO_H */

/* Define if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H 1

/* Define if you have the <sys/msgbuf.h> header file. */
/* #undef HAVE_SYS_MSGBUF_H */

/* Define if you have the <sys/select.h> header file. */
#define HAVE_SYS_SELECT_H 1

/* Define if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define if you have the <sys/utsname.h> header file. */
#define HAVE_SYS_UTSNAME_H 1

/* Define if you have <sys/wait.h> that is POSIX.1 compatible. */
#define HAVE_SYS_WAIT_H 1

/* Define if you have the <termios.h> header file. */
#define HAVE_TERMIOS_H 1

/* Define if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define if you have the `vprintf' function. */
#define HAVE_VPRINTF 1

/* Define if you have the `waitpid' function. */
#define HAVE_WAITPID 1

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* Define if the `setpgrp' function takes no argument. */
#define SETPGRP_VOID 1

/* The size of a `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG 8

/* The size of a `short', as computed by sizeof. */
#define SIZEOF_SHORT 2

/* Define if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define if the X Window System is missing or not being used. */
/* #undef X_DISPLAY_MISSING */

/* Define if `lex' declares `yytext' as a `char *' by default, not a `char[]'.
   */
#define YYTEXT_POINTER 1

/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef gid_t */

/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef uid_t */
